###
### このファイルをコピーするかリネームして config.yaml を作成してください
###

# サーバーのディレクトリパス
serverDirPath: ''

# ワールドのディレクトリ名
# Spigot環境等を考慮し、複数指定可にしています
worldDirNames:
    - ''

# GoogleDriveのアップロード先ディレクトリID
driveDirId: ''

# Minecraftサーバーの server.properties で
# enable-rcon を true に
# rcon.password に任意のパスワードを
# rcon.port に任意のポート番号を(デフォルトは25575)
rcon:
    host: ''
    port: 25575
    password: ''
